### PR TITLE
Convert zip code growing zone to a number value

### PR DESCRIPTION
**Pull request by BrandonAinsworth**
What does this PR do?
- Reformats growing_zone field from string to number

Where should your reviewer start?
- Line 11 zip_code_tables.sql
- Line 515 init.sql

What (if any) features are you implementing?
- N/A

What (if anything) did you refactor?
- Refactoring the above.

Were there any issues that arose?
- In order to match our growing zones to our zip code data, the types need to be the same.

Is there anything that you need from your teammate?
- N/A

Any other comments, questions, or concerns?
- N/A

### CODE REVIEW

**Review by Baskanbetul — APPROVED** [review]
Good job catching and correcting from string to number data!!!

**Review by rachel-bock — APPROVED** [review]
Lots of work to correct this data.  I'm wondering if there was an easier way.

**Review by irmakerdem — APPROVED** [review]
Look at all those manual changes to remove quotation marks 🥵

**Comment by Baskanbetul** [comment]
👩🏼‍💻

**Comment by Baskanbetul** [comment]
> Look at all those manual changes to remove quotation marks 🥵

🤌🏻... 🐢

**Pull request merged**
